# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/algo" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/braket" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/chem" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/circuit" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/cirq" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/core" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/honeywell" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/ionq" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/itensor" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/openfermion" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/openqasm" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/pyscf" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/qiskit" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/qulacs" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/packages/stim" # Location of package manifests
    schedule:
      interval: "daily"
