[tool.poetry]
name = "quri-parts-itensor"
version = "0.1.0"
description = "A plugin to use ITensor with QURI Parts"
authors = ["speed1313 <speedtry13@icloud.com>"]
readme = "README.md"
packages = [
    { include = "quri_parts" }
]

[tool.poetry.dependencies]
python = "3.10"
typing-extensions = "^4.4.0"
quri-parts-core = "^0.6.0"
juliacall = "^0.9.10"


[tool.poetry.group.dev.dependencies]
quri-parts-circuit = {path = "../circuit", develop = true}
quri-parts-core = {path = "../core", develop = true}

[tool.black]
line-length = 88

[tool.isort]
profile = "black"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
