[tool.poetry]
name = "itensor"
version = "0.1.0"
description = ""
authors = ["speed1313 <speedtry13@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
typing-extensions = "^4.4.0"
quri-parts-core = "^0.5.0"
juliacall = "^0.9.10"

[tool.poetry.group.dev.dependencies]
quri-parts-circuit = {path = "../circuit", develop = true}
quri-parts-core = {path = "../core", develop = true}

pytest = "^7.0.1"
black = "^22.1.0"
flake8 = "^4.0.1"
mypy = ">=0.950"
docformatter = "^1.4"
isort = "^5.10.1"
[tool.black]
line-length = 88

[tool.isort]
profile = "black"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
