name: Lint

on:
  pull_request:
    paths:
      - packages/**/*.py
      - pyproject.toml
      - poetry.lock
      - .flake8
      - .github/workflows/lint.yml
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Poetry
      env:
        POETRY_VERSION: 1.4.0
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - run: |
        poetry install --only lint

    - run: poetry run isort packages --check --diff
      if: success() || failure()

    - run: poetry run black packages --check
      if: success() || failure()

    - run: poetry run flake8 packages
      if: success() || failure()

    - run: poetry run docformatter -c -r packages
      if: success() || failure()
