name: Test

on:
  pull_request:
    paths:
      - packages/**/*.py
      - poetry.lock
      - .github/workflows/test.yml
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Poetry
      env:
        POETRY_VERSION: 1.4.0
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - run: |
        poetry install --only main,dev

    - run: poetry run julia -e 'using Pkg; Pkg.add("PythonCall")'

    - run: poetry run pytest
