name: Type check

on:
  pull_request:
    paths:
      - packages/**/*.py
      - poetry.lock
      - mypy.ini
      - .github/workflows/typecheck.yml
  push:
    branches: [main]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Poetry
      env:
        POETRY_VERSION: 1.4.0
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - run: |
        poetry install --only main,dev,typecheck

    - name: Cache mypy cache
      uses: AustinScola/mypy-cache-github-action@v1.0.0

    - run: poetry run mypy .
      if: success() || failure()
